name: go-build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build for linux
      run: GOOS=linux GOARCH=amd64 go build -mod=vendor -o mlm_linux_amd64 mlm/cmd/monitor

    - name: Build for osx
      run: GOOS=darwin GOARCH=amd64 go build -mod=vendor -o mlm_darwin_amd64 mlm/cmd/monitor
